---
- name: Playbook for infra
  hosts: web
  vars:
    env: production
    remote_role: app # define server role
  become: yes #sudo権限でコマンドを実行できる
  vars_files:
    - vars/common.yml
    - vars/production.yml
  gather_facts: false
  roles:
    - env
    - git
    - ruby
    - mysql
    - nginx
    - unicorn
